server:
  port: 7777
  servlet:
    context-path: /jqr
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jqr?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
